version: "3"

services:
  db:
    image: library/postgres:10.5-alpine
    environment:
      POSTGRES_DB: mqtt
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - 55432:5432
    volumes:
      - ./postgresql:/etc/postgresql:ro

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: rabbitmq
#    volumes:
#      - ./rabbitmq/etc/:/etc/rabbitmq/
#      - ./rabbitmq/data/:/var/lib/rabbitmq/
#      - ./rabbitmq/logs/:/var/log/rabbitmq/
#    ports:
#      - 5672:5672
#      - 15672:15672
#    depends_on:
#      - db
#    links:
#      - db

  broker:
    image: hivemq/hivemq4:latest
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - db
    links:
      - db

volumes:
  data:
    driver: local
